# mnist.toml
seed = 1337
device = "auto"
multi_gpu = false

[model]
name = "vit" 
pretrained_path = "examples/matey/pretrain-model.pth"

[data]
name = "matey"
path = ""  # folder or file later for custom dataset

[train]
batch_size = 64
num_workers = 4
init_lr = 0.001

[continuous_learning]
jvp_reg = 0.001
deltax_norm = 1
max_iter = 600

[drift_detection]
detector_name = "ADWINDetector"
detection_interval = 10  # Check drift every 10 batches
aggregation = "mean"  # Average metric over 10 batches
metric_index = 0  # Monitor loss (0=accuracy, 1=loss)
reset_after_learning = false
max_stream_updates = 20

# ADWIN hyperparameters
adwin_delta = 0.002
adwin_minor_threshold = 0.3
adwin_moderate_threshold = 0.6
