# cifar10.toml
version = "1"
seed = 1337
device = "auto"
multi_gpu = false

[model]
name = "vit16b"  
pretrained_path = "examples/cifar/cifar10_vit.pth"

[data]
name = "cifar10"
path = ""  # folder or file later for custom dataset

[train]
batch_size = 32
num_workers = 4
init_lr = 0.0001

[continuous_learning]
jvp_reg = 0.001
deltax_norm = 1
max_iter = 100

[drift_detection]
detector_name = "EvalDetector"
detection_steps = 10

[visualization]
baseline = 90.0
input = "output/cifar10_vit.csv"
output = "output/cifar10_vit_dashboard.png"