# mnist.min.toml
seed = 1337
device = "cpu"
multi_gpu = false

[model]
name = "dummy"  

[data]
name = "gray_scott"
path = ""  # folder or file later for custom dataset

[train]
batch_size = 32
num_workers = 4
init_lr = 0.001

[continuous_learning]
jvp_reg = 0.001
deltax_norm = 1
max_iter = 300

[drift_detection]
detector_name = "ADWINDetector"
detection_steps = 10

[visualization]
baseline = 90.0
input = "output/gray_scott.csv"
output = "output/gray_scott_dashboard.png"
