# mypy.ini
[mypy]
python_version = 3.12
files = src
explicit_package_bases = True

# third-party libs without typing metadata
[mypy-torchvision.*]
ignore_missing_imports = True
[mypy-torch.*]
ignore_missing_imports = True
