# mnist.min.toml
version = "1"
seed = 1337
device = "auto"
multi_gpu = false

[model]
name = "dummy"  

[data]
name = "mnist"
path = ""  # folder or file later for custom dataset

[train]
epochs = 10
batch_size = 64
num_workers = 4


[continuous_learning]
jvp_reg = 0.8
deltax_norm = 0.001
max_iter = 10