# mnist.toml
seed = 1337
device = "auto"
multi_gpu = false

[model]
name = "dummy"  
pretrained_path = "examples/mnist/mnist.pth"

[data]
name = "mnist"
path = ""  # folder or file later for custom dataset

[train]
batch_size = 64
num_workers = 1
init_lr = 0.001
max_iter = 600
grad_accumulation_steps = 2

[continual_learning]
update_mode = "base"
jvp_lambda = 10
jvp_deltax_norm = 1

# ewc hyperparameters
ewc_lambda = 1000.0
ewc_ema_decay = 0.95

# kfac hyperparameters
kfac_lambda =1e-2
kfac_ema_decay = 0.95

[drift_detection]
detector_name = "ADWINDetector"
detection_interval = 10  # Check drift every 10 batches
aggregation = "mean"  # Average metric over 10 batches
metric_index = 0  # Monitor loss (0=accuracy, 1=loss)
reset_after_learning = false
max_stream_updates = 20

# ADWIN hyperparameters
adwin_delta = 0.002
adwin_minor_threshold = 0.3
adwin_moderate_threshold = 0.6

[visualization]
baseline = 90.0
input = "output/mnist.csv"
output = "output/mnist_dashboard.png"
