name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install --no-cache-dir poetry poetry-plugin-export
        poetry export -f requirements.txt -o requirements.txt --without-hashes --with dev
        pip install --no-cache-dir -r requirements.txt && rm requirements.txt

    - name: Run ruff
      run: poetry run ruff check

    - name: Run ruff
      run: poetry run ruff format --check

    - name: Run mypy
      run: poetry run mypy .

    - name: Run tests
      run: poetry run pytest

    - name: Run mnist
      run: poetry run python -m src.main --config examples/mnist/mnist.toml

    - name: Run cifar
      run: poetry run python -m src.main --config examples/cifar/cifar10_vit.toml 